version: 3
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes: 
            - .:/var/www/html
        networks:
            - app-network
        
    db:
        image: mysql:8.0
        restart: unless-stopped

