version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes: 
            - '.:/var/www/html'
        networks:
            - app
        depends_on:
            - db
        
    db:
        image: mariadb:latest
        restart: unless-stopped
        ports:
            - '${DB_PORT:-3306}:3306'
        environment: 
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes: 
            - 'mariadb:/var/lib/mysql'
        networks:
            - app
networks:
    app:
        driver: bridge
volumes:
    mariadb:
        driver: local